import type { CudyrReportRow } from '@/types/domain/cudyrReport';
/** Empty documentary census context. No manual score, author or application time. */
export const createCudyrRecoveredRow = (
  date: string,
  name: string,
  document: string
): CudyrReportRow => ({
  key: `${date}:documentary:${document}:${name}`,
  date,
  clinicalEpisodeId: '',
  authorityDate: date,
  patientName: name,
  firstName: '',
  lastName: '',
  secondLastName: '',
  rut: document,
  documentType: '',
  diagnosis: '',
  diagnosisCode: '',
  identitySource: 'Conciliación documental',
  identitySourceDate: date,
  admissionDate: '',
  admissionTime: '',
  bedId: '',
  bedName: '',
  service: '',
  specialty: '',
  group: 'sin_grupo',
  modality: 'desconocida',
  eligibility: 'por_revisar',
  eligibilityReason: 'Contexto documental pendiente.',
  contextSource: 'verified_documentary_context',
  referenceAt: '',
  cudyrStatus: 'sin_captura',
  evaluation: null,
  evaluationCount: 0,
  lastCaptureAt: '',
  lastPersistedAt: '',
  captureActor: '',
  captureId: '',
  sourceRunId: '',
  dailyCudyrSavedAt: '',
  dailyCudyrSavedBy: '',
  medicalEpicrisisStatus: '',
  nursingEpicrisisStatus: '',
  epicrisisRegisteredAt: '',
  movements: [],
  warnings: [],
  applicationPending: false,
});
