import { addCudyrDataSheet } from './cudyrDataSheet';
import { CLINICAL_TIME_ZONE } from '@/utils/clinicalTimeZone';
import type { Workbook } from 'exceljs';
import type { CudyrReportDataset } from '@/types/domain/cudyrReport';
import {
  CUDYR_GROUP_LABELS,
  CUDYR_MODALITY_LABELS,
  CUDYR_ELIGIBILITY_LABELS,
  CUDYR_STATUS_LABELS,
  cudyrSystemDischargeLabel,
} from './cudyrReportPresentation';

export const addCudyrReportTables = (workbook: Workbook, data: CudyrReportDataset) => {
  addCudyrDataSheet(
    workbook,
    'Detalle diario',
    [
      'Fecha censo',
      'Episodio',
      'Nombre completo',
      'Nombres',
      'Apellido paterno',
      'Apellido materno',
      'RUT o documento',
      'Tipo documento',
      'Diagnóstico',
      'CIE-10',
      'Origen identidad y diagnóstico',
      'Fecha de esa identidad',
      'Ingreso fecha',
      'Ingreso hora',
      'Cama ID',
      'Cama nombre',
      'Servicio',
      'Especialidad',
      'Grupo estadístico',
      'Modalidad',
      'Elegibilidad',
      'Motivo elegibilidad',
      'Origen contexto cama',
      'Instante referencia ISO',
      'Estado CUDYR',
      'Categoría',
      'Dependencia',
      'Riesgo',
      'Evaluaciones distintas',
      'Origen CUDYR',
      'Evaluación ID origen',
      'Evaluación fecha hora ISO',
      'Autor CUDYR',
      'Autor ID',
      'Rol autor',
      'Observación archivada ID',
      'Captura fecha hora ISO',
      'Persistencia fecha hora ISO',
      'Usuario sincronizador',
      'Captura ID',
      'Ejecución origen',
      'Guardado diario HHR fecha',
      'Guardado diario HHR por',
      'Egreso sistema fecha y hora',
      'Alta real fecha',
      'Alta real hora',
      'Alta real revisada por',
      'Revisión alta fecha ISO',
      'Revisión alta motivo',
      'Revisión alta número',
      'Epicrisis médica',
      'Epicrisis enfermería',
      'Registro epicrisis ISO',
      'Observaciones',
    ],
    data.rows.map(row => [
      row.date,
      row.clinicalEpisodeId,
      row.patientName,
      row.firstName,
      row.lastName,
      row.secondLastName,
      row.rut,
      row.documentType,
      row.diagnosis,
      row.diagnosisCode,
      row.identitySource,
      row.identitySourceDate,
      row.admissionDate,
      row.admissionTime,
      row.bedId,
      row.bedName,
      row.service,
      row.specialty,
      CUDYR_GROUP_LABELS[row.group],
      CUDYR_MODALITY_LABELS[row.modality],
      CUDYR_ELIGIBILITY_LABELS[row.eligibility],
      row.eligibilityReason,
      row.contextSource,
      row.referenceAt,
      CUDYR_STATUS_LABELS[row.cudyrStatus],
      row.evaluation?.category,
      row.evaluation?.dependencyScore,
      row.evaluation?.riskScore,
      row.evaluationCount,
      row.evaluation?.source,
      row.evaluation?.sourceEvaluationId,
      row.evaluation?.recordedAt,
      row.evaluation?.author,
      row.evaluation?.authorId,
      row.evaluation?.authorRole,
      row.evaluation?.observationId,
      row.lastCaptureAt,
      row.lastPersistedAt,
      row.captureActor,
      row.captureId,
      row.sourceRunId,
      row.dailyCudyrSavedAt,
      row.dailyCudyrSavedBy,
      cudyrSystemDischargeLabel(row),
      row.correction?.actualDischarge?.date,
      row.correction?.actualDischarge?.time,
      row.correction?.updatedBy.name,
      row.correction?.updatedAt,
      row.correction?.reason,
      row.correction?.revision,
      row.medicalEpicrisisStatus,
      row.nursingEpicrisisStatus,
      row.epicrisisRegisteredAt,
      row.warnings.join(' | '),
    ])
  );
  addCudyrDataSheet(
    workbook,
    'Evaluaciones y versiones',
    [
      'Fecha censo atribuida',
      'Episodio',
      'Evento ID',
      'Observación ID',
      'Evento clave',
      'Categoría',
      'Autor',
      'Autor ID',
      'Rol autor',
      'Rol ID',
      'Fecha hora original ISO',
      'Versión opaca',
      'Anulado',
      'Dependencia',
      'Riesgo',
      'Primera captura',
      'Última verificación',
      'Capturado por',
      'Censo de captura',
      'Ejecución primera captura',
    ],
    data.observations.map(o => [
      o.censusDate,
      o.evaluation.clinicalEpisodeId,
      o.evaluation.sourceEvaluationId,
      o.id,
      o.eventKey,
      o.evaluation.category,
      o.evaluation.author,
      o.evaluation.authorId,
      o.evaluation.authorRole,
      o.evaluation.authorRoleId,
      o.evaluation.recordedAt,
      o.evaluation.sourceVersion,
      Boolean(o.evaluation.isDeleted),
      o.evaluation.dependencyScore,
      o.evaluation.riskScore,
      o.firstCapturedAt,
      o.lastVerifiedAt,
      o.firstCapturedBy,
      o.captureCensusDate,
      o.firstCaptureRunId,
    ])
  );
  addCudyrDataSheet(
    workbook,
    'Ítems CUDYR',
    [
      'Episodio',
      'Observación ID',
      'Evento ID',
      'Campo ID',
      'Campo',
      'Tipo ID',
      'Valor',
      'Fecha censo',
      'Fuente',
    ],
    [
      ...data.observations.flatMap(o =>
        (o.evaluation.items || []).map(item => [
          o.evaluation.clinicalEpisodeId,
          o.id,
          o.evaluation.sourceEvaluationId,
          item.fieldId,
          item.label,
          item.typeId,
          item.value,
          o.censusDate,
          'Eloísa · Gestión de Camas',
        ])
      ),
      ...data.rows
        .filter(row => !row.evaluation?.observationId)
        .flatMap(row =>
          (row.evaluation?.items || []).map(item => [
            row.clinicalEpisodeId,
            '',
            '',
            item.fieldId,
            item.label,
            item.typeId,
            item.value,
            row.date,
            row.evaluation?.source,
          ])
        ),
    ]
  );
  addCudyrDataSheet(
    workbook,
    'Capturas',
    [
      'Fecha censo captura',
      'Episodio',
      'Captura ID',
      'Recibo ID',
      'Estado fuente',
      'Metadatos',
      'Parte',
      'Partes totales',
      'Evaluaciones totales',
      'Observado ISO',
      'Persistido ISO',
      'Sincronizador',
      'Ejecución fuente',
      'Ejecución verificada',
    ],
    data.captures.map(c => [
      c.censusDate,
      c.capture.clinicalEpisodeId,
      c.capture.id,
      c.id,
      c.capture.status,
      c.capture.metadataStatus,
      c.capture.part,
      c.capture.totalParts,
      c.capture.totalEvaluations,
      c.capture.observedAt,
      c.receivedAt,
      c.receivedBy,
      c.capture.sourceRunId,
      c.verifiedRunId,
    ])
  );
  addCudyrDataSheet(
    workbook,
    'Asignaciones de cama',
    [
      'Episodio',
      'Recibo ID',
      'Captura fecha',
      'Asignación ID',
      'Versión opaca',
      'Cama ID',
      'Cama origen ID',
      'Cama origen nombre',
      'Servicio origen ID',
      'Servicio origen nombre',
      'Modalidad',
      'Inicio original ISO',
      'Fin original ISO',
      'Actual al capturar',
      'Anulada',
    ],
    data.captures.flatMap(c =>
      (c.capture.sourcePlacements || []).map(p => [
        p.clinicalEpisodeId,
        c.id,
        c.capture.observedAt,
        p.sourceMappingId,
        p.sourceVersion,
        p.bedId,
        p.sourceBedId,
        p.sourceBedLabel,
        p.sourceDepartmentId,
        p.sourceDepartmentLabel,
        p.modality,
        p.sourceStartAt,
        p.sourceEndAt,
        p.currentAssignment,
        p.isDeleted,
      ])
    )
  );
  const movements = [
    ...new Map(data.rows.flatMap(row => row.movements).map(m => [JSON.stringify(m), m])).values(),
  ];
  addCudyrDataSheet(
    workbook,
    'Movimientos y egresos',
    [
      'Episodio',
      'Censo observación',
      'Movimiento ID',
      'Sección',
      'Cama',
      'Nombre cama',
      'Servicio',
      'Modalidad',
      'Fecha egreso sistema',
      'Hora egreso sistema',
      'Registrado o clasificado ISO',
      'Fuente',
      'Linaje',
      'Epicrisis médica',
      'Epicrisis enfermería',
      'Registro epicrisis ISO',
    ],
    movements.map(m => [
      m.clinicalEpisodeId,
      m.censusDate,
      m.id,
      m.section,
      m.bedId,
      m.bedName,
      m.service,
      m.modality,
      m.date,
      m.time,
      m.recordedAt,
      m.source,
      m.lineageId,
      m.medicalEpicrisisStatus,
      m.nursingEpicrisisStatus,
      m.epicrisisRegisteredAt,
    ])
  );
  addCudyrDataSheet(
    workbook,
    'Auditoría altas reales',
    [
      'Episodio',
      'Revisión',
      'Alta real fecha',
      'Alta real hora',
      'Zona horaria',
      'Fecha anterior',
      'Hora anterior',
      'Motivo',
      'Autor',
      'Autor correo',
      'Autor UID',
      'Rol',
      'Registrado ISO',
      'Operación ID',
      'Censo autoridad',
    ],
    data.dischargeAudit.map(a => [
      a.clinicalEpisodeId,
      a.revision,
      a.actualDischarge?.date,
      a.actualDischarge?.time,
      CLINICAL_TIME_ZONE,
      a.previousDischarge?.date,
      a.previousDischarge?.time,
      a.reason,
      a.updatedBy.name,
      a.updatedBy.email,
      a.updatedBy.uid,
      a.updatedBy.role,
      a.updatedAt,
      a.operationId,
      a.authorityDate,
    ])
  );
  addCudyrDataSheet(
    workbook,
    'Cobertura',
    ['Fecha', 'Censo HHR', 'Última sincronización', 'Ejecución'],
    data.coverage.map(day => [day.date, day.state, day.lastSyncedAt, day.runId])
  );
};
