import path from 'node:path';
import { getEvidenceNode } from './evidenceDependencyGraph.mjs';
import { getGitReportState } from './gitReportState.mjs';
import { getReleaseEvidenceRefreshSteps } from './releaseEvidenceContract.mjs';

const SUPPORTING_GOVERNANCE_STEP_IDS = [
  'runtime-contracts',
  'serverless-runtime-governance',
  'serverless-sensitive-coverage',
  'sustainable-change-policy',
];

const getGovernanceReleaseEvidenceSteps = () => {
  // The coverage shard creates this expensive report once and CI downloads it
  // before running the governance package.
  return getReleaseEvidenceRefreshSteps({
    skipReportIds: ['critical-coverage'],
  });
};

export const GOVERNANCE_SNAPSHOT_PROFILE_BASENAME = 'ci-governance-snapshot-profile';

export const getGovernanceSnapshotSteps = () => {
  const releaseEvidenceSteps = getGovernanceReleaseEvidenceSteps();
  const supportingSteps = SUPPORTING_GOVERNANCE_STEP_IDS.filter(
    id => !releaseEvidenceSteps.some(step => step.id === id)
  ).map(id => {
    const node = getEvidenceNode(id);
    return {
      id,
      command: node?.command || `report:${id}`,
      artifacts: node?.artifacts || [],
    };
  });

  // Preserve the producer selected by the dependency-aware refresh plan. In
  // particular, release readiness must finalize from the inputs generated by
  // this same run instead of invoking its standalone nested refresh again.
  return [...releaseEvidenceSteps, ...supportingSteps];
};

export const buildGovernanceSnapshotProfile = ({ root, startedAt, completedAt, steps }) => {
  const durationMs = completedAt.getTime() - startedAt.getTime();
  const failedSteps = steps.filter(step => step.status !== 'passed');

  return {
    generatedAt: completedAt.toISOString(),
    ...getGitReportState(root),
    profile: GOVERNANCE_SNAPSHOT_PROFILE_BASENAME,
    durationMs,
    durationSeconds: Number((durationMs / 1000).toFixed(1)),
    status: failedSteps.length === 0 ? 'passed' : 'failed',
    failedSteps: failedSteps.map(step => step.id),
    steps,
    outputs: {
      json: path.join('reports', `${GOVERNANCE_SNAPSHOT_PROFILE_BASENAME}.json`),
      markdown: path.join('reports', `${GOVERNANCE_SNAPSHOT_PROFILE_BASENAME}.md`),
    },
  };
};

const formatDuration = durationMs => {
  if (durationMs < 1000) return `${durationMs}ms`;
  return `${(durationMs / 1000).toFixed(1)}s`;
};

export const formatGovernanceSnapshotProfileMarkdown = profile => `# CI Governance Snapshot Profile

- Generated: ${profile.generatedAt}
- Commit: ${profile.gitSha}
- Worktree: ${profile.gitDirty ? 'dirty' : 'clean'}
- Status: ${profile.status}
- Duration: ${formatDuration(profile.durationMs)}

## Steps

| Step | Status | Duration | Exit | Artifacts |
| --- | --- | ---: | ---: | --- |
${profile.steps
  .map(
    step =>
      `| \`${step.command}\` | ${step.status} | ${formatDuration(step.durationMs)} | ${step.exitCode ?? '-'} | ${step.artifacts.map(artifact => `\`${artifact}\``).join('<br>')} |`
  )
  .join('\n')}

## Notes

- The governance refresh generates scorecard inputs once in dependency order, then finalizes \`release-readiness-scorecard\` directly from those current inputs.
- The profile is CI evidence for the runtime cost of regenerating canonical release snapshots.
`;
