export const COMPARISON_EXCLUDE: string[] = [
  'Razon A/G',
  'Raz',
  'CHCM',
  'Conc.Hb.Corp',
  'Baciliformes',
  'Mielocitos',
  'Juveniles',
  'Blastos',
  'Promielocitos',
  'sO2c',
  'CO2 TOTAL',
  'Hora',
  'Veloc. Filtr. Glomer',
  'Veloc Filtr',
  'Deseable',
  'Indice de riesgo',
  'Glucosa promedio',
  'Normal',
  'Muy alto',
  'Recuento Hematies',
  'Basofilos',
  'Control',
  ', OT',
  'VLDL',
  'RDW',
  'Amilasa',
  'BEecf',
  'Globulinas',
  'N° de ingreso',
  'Nº de ingreso',
  'N° ingreso',
  'Nº ingreso',
  'No de ingreso',
  'Numero de ingreso',
  'MIDAS',
  'Tipo de muestra',
  'Resultado',
  'PCR SARS',
  'SARS-CoV',
  'SARS COV',
  'COVID',
  'Recuento de Colonia',
  'Recuento de Colonias',
  'Gentamicina',
];

export const COMPARISON_ORDER: string[] = [
  'Recuento Leucocitos',
  'Hemoglobina',
  'Hematocrito',
  'VCM',
  'HCM',
  'Recuento de Plaquetas',
  'Segmentados',
  'Linfocitos',
  'Monocitos',
  'Eosinofilos',
  'Proteina C Reactiva',
  'VHS',
  'LDH',
  'Creatinina',
  'RPC',
  'RAC',
  'Nitrogeno Ureico',
  'Uremia',
  'Sodio',
  'Potasio',
  'Cloro',
  'HCO3',
  'Calcio',
  'Fosforo',
  'Cuerpos Cetónicos',
  'Proteínas',
  'Nitritos',
  'Densidad',
  'Leucocitos',
  'Eritrocitos',
  'Bacterias',
  'Cilindros',
  'Placas de pus',
  'pH',
  'pCO2',
  'pO2',
  'Lactato',
  'ASAT/GOT',
  'ALAT/GPT',
  'GGT',
  'Fosfatasa Alcalina',
  'Bilirrubinas',
  'Lipasa',
  'Protrombina',
  'TTPK',
  'INR',
  'Albumina',
  'Proteinas Totales',
  'Troponina',
  'Dimero',
  'CK Total',
  'Magnesio',
  'TSH',
  'T4L',
  'T4 Libre',
  'Acido Urico',
  'Glicemia',
  'Hb glicosilada',
  'Colesterol Total',
  'LDL',
  'HDL',
  'TG',
  'Trigliceridos',
  'Cuerpos Ceton',
  'Cetonemia',
];
