export const ANALYSIS_NAME_REPLACEMENTS: [RegExp, string][] = [
  [/HCO3\s*ACTUAL/i, 'HCO3'],
  [/Hb\.\s*Corp\.\s*Media\s*-\s*HCM/i, 'HCM'],
  [/Vol\.\s*Corp\.\s*Medio\s*VCM/i, 'VCM'],
  [/^\s*Leucocitos(?:\s+totales)?\s*$/i, 'Recuento Leucocitos'],
  [/^\s*Rcto\.?\s*Leucocitos\s*$/i, 'Recuento Leucocitos'],
  [/^\s*Plaquetas\s*$/i, 'Recuento de Plaquetas'],
  [/^\s*Neutr[oó]filos(?:\s+segmentados)?\s*$/i, 'Segmentados'],
  [/^\s*Creatinina(?:\s+s[eé]rica)?\s*$/i, 'Creatinina'],
  [/^\s*PCR\s*$/i, 'Proteina C Reactiva'],
  [/^\s*Prot\.?\s*C\.?\s*Reactiva\s*$/i, 'Proteina C Reactiva'],
  [/^\s*(?:CK|CPK|Creatin(?:a\s+)?(?:fosfo)?(?:quinasa|kinasa))(?:\s+Total)?\s*$/i, 'CK Total'],
  [/^\s*Hemoglobina\s+Glicosilada(?:\s*#?\d*)?\s*$/i, 'Hb glicosilada'],
  [/^\s*Triglic(?:#|e|é)ridos\s*$/i, 'Trigliceridos'],
  [/^\s*(?:Rel(?:aci[oó]n|ac\.?|\.?)\s*)?Proteinuria\s*\/\s*Creatininuria\s*[:=]?\s*$/i, 'RPC'],
  [
    /^\s*(?:Rel(?:aci[oó]n|ac\.?|\.?)\s*)?Albumina\s*\/\s*Creatin(?:in)?uri[a]?\s*[:=]?\s*$/i,
    'RAC',
  ],
  [/^\s*Bilirrubina\s+T\.?\s*$/i, 'Bilirrubina Total'],
  [/^\s*Bilirrubina\s+D\.?\s*$/i, 'Bilirrubina Directa'],
  [/^\s*Bilirrubina\s+I\.?\s*$/i, 'Bilirrubina Indirecta'],
];
