import { AuditAction } from '@/types/auditActionTypes';

export const CRITICAL_ACTIONS: AuditAction[] = [
  'PATIENT_ADMITTED',
  'PATIENT_DISCHARGED',
  'PATIENT_TRANSFERRED',
  'PATIENT_DISCHARGE_DIAGNOSIS_CHANGED',
  'PATIENT_DISCHARGE_RECLASSIFIED',
  'PATIENT_BED_CHANGED',
  'DAILY_RECORD_DELETED',
];

export const IMPORTANT_ACTIONS: AuditAction[] = [
  'PATIENT_MODIFIED',
  'PATIENT_DIAGNOSIS_CHANGED',
  'CUDYR_MODIFIED',
  'CUDYR_BATCH_SAVED',
  'NURSE_HANDOFF_MODIFIED',
  'MEDICAL_HANDOFF_MODIFIED',
  'HANDOFF_NOVEDADES_MODIFIED',
  'MEDICAL_HANDOFF_RESTORED',
  'PREVIOUS_DAY_EDIT_CONFIRMED',
];

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  PATIENT_ADMITTED: 'Ingreso de Paciente',
  PATIENT_DISCHARGED: 'Alta de Paciente',
  PATIENT_TRANSFERRED: 'Traslado de Paciente',
  PATIENT_MODIFIED: 'Modificación de Datos',
  PATIENT_BED_CHANGED: 'Cambio de Cama',
  PATIENT_DIAGNOSIS_CHANGED: 'Cambio de Diagnóstico',
  PATIENT_DISCHARGE_DIAGNOSIS_CHANGED: 'Cambio de Diagnóstico de Egreso',
  PATIENT_DISCHARGE_RECLASSIFIED: 'Reclasificación de Egreso',
  PATIENT_CLEARED: 'Limpieza de Cama',
  DAILY_RECORD_DELETED: 'Eliminación de Registro',
  DAILY_RECORD_CREATED: 'Creación de Registro',
  PREVIOUS_DAY_EDIT_CONFIRMED: 'Edición de día anterior confirmada',
  PRESCRIPTION_MANUAL_DELETED: 'Receta eliminada manualmente',
  PRESCRIPTION_RETENTION_DELETED: 'Receta eliminada por proceso automático histórico',
  MEDICAL_INDICATION_RECORD_CREATED: 'Indicaciones médicas generadas',
  MEDICAL_INDICATION_TEMPLATE_CREATED: 'Indicación personal creada',
  MEDICAL_INDICATION_TEMPLATE_UPDATED: 'Indicación personal editada',
  MEDICAL_INDICATION_TEMPLATE_ARCHIVED: 'Indicación personal archivada',
  MEDICAL_INDICATION_TEMPLATE_USED: 'Indicación personal reutilizada',
  VIEW_PATIENT: 'Visualización de Ficha',
  PATIENT_VIEWED: 'Visualización de Ficha (Legacy)',
  NURSE_HANDOFF_MODIFIED: 'Nota Enfermería (Entrega)',
  MEDICAL_HANDOFF_MODIFIED: 'Nota Médica (Entrega)',
  HANDOFF_NOVEDADES_MODIFIED: 'Cambio en Novedades',
  CUDYR_MODIFIED: 'Evaluación CUDYR',
  CUDYR_BATCH_SAVED: 'Guardado CUDYR',
  CLINICAL_DOCUMENT_CREATED: 'Documento clínico creado',
  CLINICAL_DOCUMENT_DELETED: 'Documento clínico eliminado',
  CLINICAL_DOCUMENT_EDITED: 'Documento clínico editado',
  CLINICAL_DOCUMENT_LOCKED: 'Documento clínico bloqueado',
  USER_LOGIN: 'Inicio de Sesión',
  USER_LOGOUT: 'Cierre de Sesión',
  BED_BLOCKED: 'Cama Bloqueada',
  BED_UNBLOCKED: 'Cama Desbloqueada',
  EXTRA_BED_TOGGLED: 'Cama Extra Toggled',
  MEDICAL_HANDOFF_SIGNED: 'Firma Entrega Médica',
  MEDICAL_HANDOFF_RESTORED: 'Restauración Entrega Médica',
  VIEW_CUDYR: 'Visualización CUDYR',
  VIEW_NURSING_HANDOFF: 'Visualización Entrega Enfermería',
  VIEW_MEDICAL_HANDOFF: 'Visualización Entrega Médica',
  PATIENT_NOTE_UPDATED: 'Nota del Paciente Actualizada',
  CLINICAL_EVENT_ADDED: 'Evento Clínico Agregado',
  CLINICAL_EVENT_UPDATED: 'Evento Clínico Actualizado',
  CLINICAL_EVENT_DELETED: 'Evento Clínico Eliminado',
  DATA_IMPORTED: 'Importación de Datos',
  DATA_EXPORTED: 'Exportación de Datos',
  PATIENT_HARMONIZED: 'Armonización de Identidad',
  CONFLICT_AUTO_MERGED: 'Conflicto Auto-Resuelto',
  CONFLICT_VERSION_RESTORED: 'Versión Restaurada',
  DATA_ADMISSION_DATES_BACKFILLED: 'Corrección Fechas de Ingreso',
  PATIENT_SPECIALTY_CHANGED: 'Cambio de Especialidad',
  STATISTICAL_SPECIALTY_RECLASSIFIED: 'Reclasificación estadística',
  WOUND_CARE_PHOTO_UPLOADED: 'Foto clínica subida',
  CLINICAL_DOCUMENT_EXPORTED: 'Documento clínico exportado',
  CLINICAL_DOCUMENT_PRINTED: 'Documento clínico impreso',
  SYSTEM_ERROR: 'Error del Sistema',
};
