import type { AuditAction } from '@/types/auditActionTypes';

export const VIEW_AUDIT_ACTIONS = new Set<AuditAction>([
  'VIEW_PATIENT',
  'PATIENT_VIEWED',
  'VIEW_CUDYR',
  'VIEW_NURSING_HANDOFF',
  'VIEW_MEDICAL_HANDOFF',
]);

export const DOCUMENT_AUDIT_ACTIONS = new Set<AuditAction>([
  'CLINICAL_DOCUMENT_CREATED',
  'CLINICAL_DOCUMENT_DELETED',
  'CLINICAL_DOCUMENT_EDITED',
  'CLINICAL_DOCUMENT_EXPORTED',
  'CLINICAL_DOCUMENT_PRINTED',
  'CLINICAL_DOCUMENT_LOCKED',
  'WOUND_CARE_PHOTO_UPLOADED',
]);

export const MEDICATION_AUDIT_ACTIONS = new Set<AuditAction>([
  'PRESCRIPTION_MANUAL_DELETED',
  'PRESCRIPTION_RETENTION_DELETED',
  'MEDICAL_INDICATION_RECORD_CREATED',
  'MEDICAL_INDICATION_TEMPLATE_CREATED',
  'MEDICAL_INDICATION_TEMPLATE_UPDATED',
  'MEDICAL_INDICATION_TEMPLATE_ARCHIVED',
  'MEDICAL_INDICATION_TEMPLATE_USED',
]);
